import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip"
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { Toaster } from "sonner";
import { Suspense } from "react";
import { NavbarWrapper, FooterWrapper } from "@/components/navbar-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { ChatWidgetWrapper } from "@/components/ChatWidgetWrapper";
import { ThemeColorsProvider } from "@/components/theme-colors-provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <ConvexAuthNextjsServerProvider>
        <html
          lang="en"
          className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, jetbrainsMono.variable, "font-sans", inter.variable)}
          suppressHydrationWarning
        >
          <head>

          </head>
          <body className="min-h-full flex flex-col">
            <ConvexClientProvider>
              <ThemeProvider defaultTheme="system" storageKey="nextjs-convex-auth-theme">
                <ThemeColorsProvider />
                <Toaster closeButton />
                <TooltipProvider>
                  <NavbarWrapper />
                  <main className="flex-1">
                    {children}
                  </main>
                  <FooterWrapper />
                  <ChatWidgetWrapper />
                </TooltipProvider>

              </ThemeProvider>
            </ConvexClientProvider>
          </body>
        </html>
      </ConvexAuthNextjsServerProvider>
    </Suspense>
  );
}
